=encoding utf8

=head1 Changes in Parse::DNS::Zone

=head2 Next release

=head3 Documentation

=over

=item * Changed the GPL text in LICENSE to GPL-1 (2011-02-13)

Note that this isn't a change in what license the module is relased
under. It is, and has always been, Artistic License or GPL-1 or later.

=item * Documented availability (CPAN, Github) in POD and README (2011-02-24)

=back

=head2 0.41 (2011-01-07)

=over 

=item * Origin is now appended in RDATA (thanks to Sebastian 
        Hagedorn at Universität zu Köln).

=item * Some minor documentation fixes

=back

=head2 0.4 (2010-11-21)

=over

=item * get_rdata returns a list of complete RRset in list context.
B<Please be aware that this may break existing code.> Sorry :-(

=item * Fixes to documentation (new mail address, <olof@cpan.org>)

=back

=head2 0.3 (2010-04-18)

=over

=item * Added real tests (t/03-parser.t)

=item * Possibility to get either class, ttl or rdata when calling
get_rdata(). (Thanks to Mark J. Reed)

=item * Fixed a bug with get_dupes(), trying to int() on an arrayref 
instead of the array (Thanks to Mark J. Reed)

=item * Fixed bugs in documentation

=item * Fixed RFC compliance bug, not supporting the format 
"<name> <class> <ttl> <type> <rdata>"

=back

=head2 0.23 (2009-11-15) (Never released)

=over

=item * Added a LICENSE file 

=item * Added POD tests 

=back

=head2 0.22 (2009-11-14)

=over

=item * Fixed a bug where you can't use @ as an argument to get_rdata

=item * Fixed bug where no parsing of arguments is done 
on get_rrs and exists

=back

=head2 0.21 (2009-11-14)

=over

=item * First published version

=item * Fixed a bug in $origin parsing, not possible to have dots in it

=back

=head2 0.20 (2009-11-13)

=over

=item * Fixed support for multiple RRs with same type for same name

=item * Testing with Test::Distribution

=back

=head2 0.1 (2009-09-13)

=over

=item * Packaged the module

=back
